/* 
 * File:   UDPCommands.h
 * Author: Pete
 *
 * Created on 3 September 2024
 */

#ifndef UDPCOMMANDS_H
#define	UDPCOMMANDS_H

#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

typedef enum {
    UDPCOMMANDS_NONE = 0,
    UDPCOMMANDS_HANDSHAKE,
    UDPCOMMANDS_POWER,
    UDPCOMMANDS_RTCM3,
    UDPCOMMANDS_FLIGHT_CONTROL,
    UDPCOMMANDS_MISSION,
    UDPCOMMANDS_SET_ID,
    UDPCOMMANDS_SET_LED_RGB,
    UDPCOMMANDS_SET_WIFI,
    UDPCOMMANDS_CHECK_PREARM,
    UDPCOMMANDS_CALIBRATE,
    UDPCOMMANDS_SET_FENCE,
    UDPCOMMANDS_SET_RTL_ALTITUDE,
    UDPCOMMANDS_TEST_MOTORS,
    UDPCOMMANDS_PLAN,
    UDPCOMMANDS_PARAM,
    UDPCOMMANDS_FIRMWARE,
    UDPCOMMANDS_UAV_INFO,
    UDPCOMMANDS_BATTERY_VOLTAGE,
    UDPCOMMANDS_COUNT // This is used to count the number of commands
} UDPCommand;

bool IsValidUDPCommand(uint8_t command_byte);

#endif	/* UDPCOMMANDS_H */

